mose/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("wizuber/", include("wizuber.urls")),
]

wizuber/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import TemplateView

import wizuber.views as views

app_name = "wizuber"

urlpatterns = [
    path("", TemplateView.as_view(template_name="wizuber/index.html"), name="index"),
    path("account/", views.account.DetailAccount.as_view(), name="account"),
    path("account/login/", views.account.LoginAccount.as_view(), name="login"),
    path("account/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("account/signup/", views.account.CustomerSignUp.as_view(), name="signup"),
    path("wizard/list/", views.wizard.ListWizard.as_view(), name="list-wizard"),
    path("wizard/<int:pk>/", views.wizard.DetailWizard.as_view(), name="detail-wizard"),
    path("wish/list/", views.wish.ListWish.as_view(), name="list-wish"),
    path(
        "wish/list/active/",
        views.wish.ListWishActive.as_view(),
        name="list-wish-active",
    ),
    path(
        "wish/list/closed/",
        views.wish.ListWishClosed.as_view(),
        name="list-wish-closed",
    ),
    path("wish/create/", views.wish.CreateWish.as_view(), name="create-wish"),
    path("wish/<int:pk>/", views.wish.DetailWish.as_view(), name="detail-wish"),
    path(
        "wish/<int:pk>/handle/<str:action>",
        views.wish.HandleWishAction.as_view(),
        name="handle-wish-action",
    ),
    path(
        "artifact/<int:pk>/delete/",
        views.artifact.DeleteArtifact.as_view(),
        name="delete-artifact",
    ),
]

wizuber/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from polymorphic.managers import PolymorphicManager
from polymorphic.models import PolymorphicModel

from wizuber.const import CUSTOMER_PERM, SPIRIT_PERM, STUDENT_PERM, WIZARD_PERM
from wizuber.helpers import ChoicesEnum


class PolymorphicUserManager(PolymorphicManager, UserManager):
    pass


class WizuberUser(PolymorphicModel, AbstractUser):
    first_name = models.CharField(_("first name"), max_length=30, blank=False)
    last_name = models.CharField(_("last name"), max_length=30, blank=False)
    middle_name = models.CharField(
        _("middle name"), max_length=30, null=True, blank=True
    )
    email = models.EmailField(_("email address"), blank=False, unique=True)

    REQUIRED_FIELDS = ["first_name", "last_name", "email"]

    objects = PolymorphicUserManager()

    class Meta:
        ordering = ["id"]

    def get_queryset_for_wish_list(self):
        return Wish.objects.none()

    def can_view_wish(self, wish: "Wish") -> bool:
        return False

    is_wizard = False
    is_customer = False
    is_student = False
    is_spirit = False
    type_name = "admin"


class Wizard(WizuberUser):
    balance = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ["id"]

    is_wizard = True
    type_name = "wizard"

    def has_student(self) -> bool:
        return hasattr(self, "student")

    def get_absolute_url(self):
        return reverse("wizuber:detail-wizard", kwargs=dict(pk=self.id))

    def get_queryset_for_wish_list(self):
        return self.owned_wishes.exclude(status=Wish.STATUSES.CLOSED.name)

    def can_view_wish(self, wish: "Wish") -> bool:
        return wish.in_status(wish.STATUSES.ACTIVE) or self == wish.owner


class Customer(WizuberUser):
    balance = models.PositiveIntegerField(default=500)

    class Meta:
        ordering = ["id"]

    is_customer = True
    type_name = "customer"

    def get_queryset_for_wish_list(self):
        return self.created_wishes.exclude(status=Wish.STATUSES.CLOSED.name)

    def can_view_wish(self, wish: "Wish") -> bool:
        return self == wish.creator


class Student(WizuberUser):
    teacher = models.OneToOneField(Wizard, on_delete=models.PROTECT)

    class Meta:
        ordering = ["id"]

    is_student = True
    type_name = "student"

    def get_queryset_for_wish_list(self):
        return self.assigned_wishes.all()

    def can_view_wish(self, wish: "Wish") -> bool:
        return self.teacher.can_view_wish(wish)


class SpiritGrades(ChoicesEnum):
    IMP = "Imp"
    FOLIOT = "Foliot"
    DJINNI = "Djinni"
    AFRIT = "Afrit"
    MARID = "Marid"

    @classmethod
    def default(cls):
        return super().default()


class Spirit(WizuberUser):
    master = models.ForeignKey(
        Wizard, on_delete=models.SET_NULL, null=True, blank=True, default=None
    )
    GRADES = SpiritGrades
    grade = models.CharField(max_length=GRADES.max_length(), choices=GRADES.choices())

    class Meta:
        ordering = ["id"]

    is_spirit = True
    type_name = "spirit"

    def get_queryset_for_wish_list(self):
        return self.assigned_wishes.all()

    def can_view_wish(self, wish: "Wish") -> bool:
        return self == wish.assigned_to


class WishStatus(ChoicesEnum):
    NEW = "New"
    ACTIVE = "Active"
    WORK = "Work"
    ON_SPIRIT = "On Spirit"
    READY = "Ready"
    CLOSED = "Closed"

    @classmethod
    def default(cls):
        return cls.NEW.name


class Wish(models.Model):
    creator = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name="created_wishes"
    )
    description = models.TextField()
    owner = models.ForeignKey(
        Wizard,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="owned_wishes",
    )
    STATUSES = WishStatus
    status = models.CharField(
        max_length=STATUSES.max_length(),
        choices=STATUSES.choices(),
        default=STATUSES.default(),
    )
    assigned_to = models.ForeignKey(
        WizuberUser,
        related_name="assigned_wishes",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    price = models.PositiveIntegerField(
        validators=[MinValueValidator(limit_value=1)], default=50
    )

    class Meta:
        ordering = ["id"]

    def get_absolute_url(self):
        return reverse("wizuber:detail-wish", kwargs=dict(pk=self.id))

    def has_spirit_artifact(self) -> bool:
        return hasattr(self, "spirit_artifact")

    def in_status(self, status: WishStatus) -> bool:
        return self.status == status.name


class BaseArtifact(PolymorphicModel):
    class Meta:
        ordering = ["id"]


class SizeChoices(ChoicesEnum):
    LARGE = "large"
    MEDIUM = "medium"
    SMALL = "small"

    @classmethod
    def default(cls):
        return cls.MEDIUM.name


class CandleMaterial(ChoicesEnum):
    TALLOW = "tallow"
    BEESWAX = "beeswax"
    PARAFFIN = "paraffin"

    @classmethod
    def default(cls):
        return cls.TALLOW.name


class CandleArtifact(BaseArtifact):
    wish = models.ForeignKey(
        Wish, related_name="candle_artifacts", on_delete=models.CASCADE
    )
    SIZES = SizeChoices
    size = models.CharField(
        max_length=SIZES.max_length(), choices=SIZES.choices(), default=SIZES.default()
    )
    MATERIALS = CandleMaterial
    material = models.CharField(
        max_length=MATERIALS.max_length(),
        choices=MATERIALS.choices(),
        default=MATERIALS.default(),
    )

    class Meta:
        ordering = ["id"]


class PentacleArtifact(BaseArtifact):
    wish = models.ForeignKey(
        Wish, related_name="pentacle_artifacts", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)
    SIZES = SizeChoices
    size = models.CharField(
        max_length=SIZES.max_length(), choices=SIZES.choices(), default=SIZES.default()
    )

    class Meta:
        ordering = ["id"]


class SpiritArtifact(BaseArtifact):
    wish = models.OneToOneField(
        Wish, related_name="spirit_artifact", on_delete=models.CASCADE
    )
    spirit = models.ForeignKey(
        Spirit, related_name="spirit_artifacts", on_delete=models.PROTECT
    )

    class Meta:
        ordering = ["id"]


class RightsSupport(models.Model):
    class Meta:
        # No database table creation or deletion operations
        # will be performed on this model.
        managed = False
        permissions = (
            (CUSTOMER_PERM, "Global customer rights"),
            (WIZARD_PERM, "Global wizard rights"),
            (STUDENT_PERM, "Global student rights"),
            (SPIRIT_PERM, "Global spirit rights"),
        )

wizuber/forms.py
from django.contrib.auth.forms import UserCreationForm

from wizuber.models import Customer


class CustomerSignUpForm(UserCreationForm):
    required_css_class = "required-label-asterisk"

    class Meta(UserCreationForm.Meta):
        model = Customer
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "middle_name",
            "password1",
            "password2",
        )

wizuber/views/account.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import TemplateView

from wizuber.forms import CustomerSignUpForm
from wizuber.views.helpers import PageTitleMixin


class DetailAccount(LoginRequiredMixin, PageTitleMixin, TemplateView):
    template_name = "wizuber/account/detail.html"
    page_title = "Account"


class LoginAccount(PageTitleMixin, LoginView):
    template_name = "wizuber/account/login.html"
    page_title = "Login"


class CustomerSignUp(PageTitleMixin, generic.CreateView):
    form_class = CustomerSignUpForm
    success_url = reverse_lazy("wizuber:index")
    template_name = "wizuber/account/signup.html"

    page_title = "Sign up"

wizuber/views/artifact.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DeleteView

from wizuber.models import BaseArtifact


class DeleteArtifact(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = BaseArtifact

    http_method_names = ["post", "delete", "head", "options", "trace"]

    def test_func(self):
        user, wish = self.request.user, self.get_object().wish
        is_work_status = wish.status == wish.STATUSES.WORK.name

        if is_work_status and user.is_wizard and user == wish.owner == wish.assigned_to:
            return True

        if (
            is_work_status
            and user.is_student
            and wish.owner == user.teacher
            and user == wish.assigned_to
        ):
            return True

        return False

    def get_success_url(self):
        return self.object.wish.get_absolute_url()

wizuber/views/helpers.py
from django.views.generic.base import ContextMixin


class PageTitleMixin(ContextMixin):
    page_title = ""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.page_title:
            context["page_title"] = self.page_title
        return context

wizuber/views/wish.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpRequest
from django.shortcuts import redirect
from django.views import generic

from wizuber.fsm import (
    ActionAccessDenied,
    ActionNotFound,
    action_class_by_name,
    action_classes,
)
from wizuber.models import Wish
from wizuber.views.helpers import PageTitleMixin

logger = logging.getLogger(__name__)


class ListWish(LoginRequiredMixin, PageTitleMixin, generic.ListView):
    """
    Returns list of wishes. For specific types of users returns different results:
    Customer: wishes created by him;
    Wizard: wishes owned by him;
    Student: wishes assigned to him;
    Spirit: wishes assigned to him;
    """

    page_title = "Wishes List"
    model = Wish
    context_object_name = "wishes"
    template_name = "wizuber/wish/list.html"
    paginate_by = 10

    def get_queryset(self):
        return self.request.user.get_queryset_for_wish_list()


class ListWishActive(UserPassesTestMixin, ListWish):
    """
    Returns wish list for wizard (only with "active" status).
    Represents "new orders" page.
    """

    page_title = "Available Wishes For Order"

    def test_func(self):
        return self.request.user.is_wizard

    def get_queryset(self):
        return Wish.objects.filter(status=Wish.STATUSES.ACTIVE.name)


class ListWishClosed(ListWishActive):
    """ Returns customer`s wish list with closed statuses. """

    page_title = "Closed Wishes"

    def test_func(self):
        return self.request.user.is_customer

    def get_queryset(self):
        return Wish.objects.filter(
            status=Wish.STATUSES.CLOSED.name, creator=self.request.user
        )


class CreateWish(
    LoginRequiredMixin, UserPassesTestMixin, PageTitleMixin, generic.CreateView
):
    page_title = "Create New Wish"
    model = Wish
    fields = ["description", "price"]
    template_name = "wizuber/wish/create.html"

    def test_func(self):
        return self.request.user.is_customer

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class DetailWish(
    LoginRequiredMixin, UserPassesTestMixin, PageTitleMixin, generic.DetailView
):
    page_title = "Wish Details"
    model = Wish
    context_object_name = "wish"
    template_name = "wizuber/wish/detail.html"

    def test_func(self):
        return self.request.user.can_view_wish(self.get_object())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["actions"] = self.get_actions()
        return context

    def get_actions(self):
        wish, user = self.object, self.request.user
        action_instances = (cls(wish, user) for cls in action_classes())
        return [action for action in action_instances if action.is_available()]


class HandleWishAction(
    LoginRequiredMixin, generic.View, generic.detail.SingleObjectMixin
):
    model = Wish

    def post(self, request: HttpRequest, pk: int, action: str):
        logger.info(
            'action "%s" for wish "%s" from user "%s"', action, pk, self.request.user
        )
        try:
            action_class = action_class_by_name(action)
        except ActionNotFound:
            raise Http404
        action = action_class(wish=self.get_object(), user=self.request.user)
        try:
            action.execute(request)
        except ActionAccessDenied:
            raise PermissionDenied from None
        return redirect(action.get_success_url())

wizuber/views/wizard.py
from django.views import generic

from wizuber.models import Wizard
from wizuber.views.helpers import PageTitleMixin


class ListWizard(PageTitleMixin, generic.ListView):
    template_name = "wizuber/wizard/list.html"
    context_object_name = "wizards"
    page_title = "Wizard List"
    paginate_by = 10

    def get_queryset(self):
        return Wizard.objects.all()


class DetailWizard(PageTitleMixin, generic.DetailView):
    model = Wizard
    template_name = "wizuber/wizard/detail.html"
    page_title = "Wizard Details"

wizuber/templates/wizuber/action/base.html
<div class="row py-2">
    <div class="col">
        <form action="{% url 'wizuber:handle-wish-action' wish.pk action.get_action_name %}"
              name="{{ action.get_action_name }}" method="POST">
            {% csrf_token %}

            {% block main %}
            {% endblock %}

        </form>
    </div>
</div>

{% block bottom %}
{% endblock %}

wizuber/templates/wizuber/action/candle-artifact.html
{% extends 'wizuber/action/base.html' %}

{% block main %}
    {% with form=action.get_form %}
        <div class="form-row">
            <div class="form-group col-auto">
                {% include 'wizuber/signup_form_field.html' with field=form.size %}
            </div>
            <div class="form-group col-auto">
                {% include 'wizuber/signup_form_field.html' with field=form.material %}
            </div>
        </div>
    {% endwith %}

    <button type="submit" class="btn btn-outline-primary">Add candle</button>
{% endblock %}

{% block bottom %}
    {% if wish.candle_artifacts.all %}
        <div class="row py-2">
            <div class="col">
                <table class="table table-sm table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Size</th>
                        <th scope="col">Material</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for artifact in wish.candle_artifacts.all %}
                        <tr>
                            <th class="align-middle" scope="row">{{ forloop.counter }}</th>
                            <td class="align-middle">{{ artifact.size | title }}</td>
                            <td class="align-middle">{{ artifact.material | title }}</td>
                            <td class="align-middle">
                                <form action="{% url 'wizuber:delete-artifact' artifact.pk %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
{% endblock %}

wizuber/templates/wizuber/action/close.html
{% extends 'wizuber/action/base.html' %}

{% block main %}

    <button type="submit" class="btn btn-outline-danger">Close wish</button>

{% endblock %}

wizuber/templates/wizuber/action/delete.html
{% extends 'wizuber/action/base.html' %}

{% block main %}

    <button type="submit" class="btn badge-danger">Delete wish</button>

{% endblock %}

wizuber/templates/wizuber/action/own.html
{% extends 'wizuber/action/base.html' %}

{% block main %}

    <div class="form-row">
        <div class="col-auto">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">£</span>
                </div>
                <input type="text" class="form-control" value="{{ wish.price }}" aria-label="price amount"
                       disabled>
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-primary">Take ownership</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

wizuber/templates/wizuber/action/pay.html
{% extends 'wizuber/action/base.html' %}

{% block main %}

    <div class="form-row">
        <div class="col-auto">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">£</span>
                </div>
                <input type="text" class="form-control" value="{{ wish.price }}" aria-label="price amount" disabled>
                {% if wish.price <= user.balance %}
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-success">Pay for wish</button>
                    </div>
                {% endif %}
            </div>
            {% if wish.price > user.balance %}
                <small>You dont have enough money to pay for this wish.</small>
            {% endif %}
        </div>
    </div>

{% endblock %}

wizuber/templates/wizuber/action/pentacle-artifact.html
{% extends 'wizuber/action/base.html' %}

{% block main %}
    {% with form=action.get_form %}
        <div class="form-row">
            <div class="form-group col-auto">
                {% include 'wizuber/signup_form_field.html' with field=form.name %}
            </div>
            <div class="form-group col-auto">
                {% include 'wizuber/signup_form_field.html' with field=form.size %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group">
                {% include 'wizuber/signup_form_field.html' with field=form.description %}
            </div>
        </div>
    {% endwith %}

    <button type="submit" class="btn btn-outline-primary">Add pentacle</button>
{% endblock %}

{% block bottom %}
    {% if wish.pentacle_artifacts.all %}
        <div class="row py-2">
            <div class="col">
                <table class="table table-sm table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Size</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for artifact in wish.pentacle_artifacts.all %}
                        <tr>
                            <th class="align-middle" scope="row">{{ forloop.counter }}</th>
                            <td class="align-middle">{{ artifact.name }}</td>
                            <td class="align-middle">{{ artifact.size | title }}</td>
                            <td class="align-middle">
                                <form action="{% url 'wizuber:delete-artifact' artifact.pk %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
{% endblock %}

wizuber/templates/wizuber/action/spirit-artifact.html
{% extends 'wizuber/action/base.html' %}

{% block main %}
    {% if not wish.spirit_artifact %}
        {% with form=action.get_form %}
            <div class="form-row">
                <div class="form-group col-auto">
                    {% include 'wizuber/signup_form_field.html' with field=form.spirit %}
                </div>
            </div>
        {% endwith %}

        <button type="submit" class="btn btn-outline-primary">Add spirit</button>
    {% endif %}
{% endblock %}

{% block bottom %}
    {% if wish.spirit_artifact %}
        <div class="row py-2">
            <div class="col">
                <table class="table table-sm table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Spirit Username</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th class="align-middle" scope="row">1</th>
                        <td class="align-middle">{{ wish.spirit_artifact.spirit.username }}</td>
                        <td class="align-middle">
                            <form action="{% url 'wizuber:delete-artifact' wish.spirit_artifact.pk %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                            </form>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
{% endblock %}

wizuber/templates/wizuber/action/spirit-to-wizard.html
{% extends 'wizuber/action/base.html' %}

{% block main %}

    <div class="form-row">
        <div class="col-auto">
            <div class="input-group">
                <input type="text" class="form-control" value="{{ wish.owner }}" aria-label="wizard username" disabled>
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-primary">Assign back to wizard</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

wizuber/templates/wizuber/action/to-spirit.html
{% extends 'wizuber/action/base.html' %}

{% block main %}

    <div class="form-row">
        <div class="col-auto">
            <div class="input-group">
                <input type="text" class="form-control" value="{{ wish.spirit_artifact.spirit }}"
                       aria-label="spirit username" disabled>
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-primary">Assign to spirit</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

wizuber/templates/wizuber/action/to-student.html
{% extends 'wizuber/action/base.html' %}

{% block main %}

    <div class="form-row">
        <div class="col-auto">
            <div class="input-group">
                <input type="text" class="form-control" value="{{ user.student }}" aria-label="price amount"
                       disabled>
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-primary">Assign to student</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

wizuber/templates/wizuber/action/to-wizard.html
{% extends 'wizuber/action/base.html' %}

{% block main %}

    <div class="form-row">
        <div class="col-auto">
            <div class="input-group">
                <input type="text" class="form-control" value="{{ user.teacher }}" aria-label="price amount"
                       disabled>
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-primary">Assign back to teacher</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}